name: tests
on:
  push:
    branches: [main]
env:
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-targets --all-features
  build-musl:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install clang-18
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - run: TARGET_CC=clang-18 TARGET_AR=llvm-ar-18 cargo build --all-targets --all-features --target x86_64-unknown-linux-musl
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-targets --all-features
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cross
      - run: cross check --all-targets --target aarch64-linux-android --no-default-features
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  test-musl:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install clang-18
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - run: TARGET_CC=clang-18 TARGET_AR=llvm-ar-18 cargo test --all-features --target x86_64-unknown-linux-musl
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-deny
      - run: cargo clippy --all-targets --all-features -- -Dwarnings
      - run: cargo fmt --check
      - run: cargo deny check
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: RUSTDOCFLAGS="-Dwarnings" cargo doc --all-features
      - run: cargo test --doc --all-features

  build2:
    needs:
      - test
      - test-macos
      - lint
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build (${{ matrix.os }}${{ matrix.arch && format(' {0}', matrix.arch) || ''}})"
    strategy:
      matrix:
        include:
          - os: ubuntu
          - os: ubuntu
            arch: arm
          - os: macos
    runs-on: ${{ matrix.arch && format('ubuntu-24.04-{0}', matrix.arch) || format('{0}-latest', matrix.os) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Compile
        run: cargo +stable build --release
      - name: Archive executables
        run: tar -czf rbw-$(uname)-$(uname -m).tar.gz target/release/rbw target/release/rbw-agent
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: executable-${{ runner.os }}-${{ runner.arch }}
          path: rbw-*

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build2
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          pattern: 'executable-*'
          merge-multiple: true
      - name: Set version
        run: echo "RELEASE_VERSION=$(cargo pkgid | cut -d# -f2)" >> "$GITHUB_ENV"
      - name: Check version
        run: 'echo "Release version: ${{ env.RELEASE_VERSION }}"'
      - name: Delete existing release and tag
        run: |
          gh release delete "${{ env.RELEASE_VERSION }}" --yes --cleanup-tag || echo "Release ${{ env.RELEASE_VERSION }} does not exist"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'executable-*'
          removeArtifacts: true
          replacesArtifacts: true
          tag: ${{ env.RELEASE_VERSION }}
